version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_customer
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: customer
      MYSQL_USER: k2k2
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendahub_customer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_customer:3306/customer
      SPRING_DATASOURCE_USERNAME: k2k2
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"  # Colocar true entre aspas
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
