server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://customer-database.c5syiyqysxgo.sa-east-1.rds.amazonaws.com:3306/customer
    username: agendahub_customer_admin
    password: italok2k2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
